namespace Long.Kernel.Scripting.LUA
{
    public class LuaScriptConst
    {
        public const int G_PLAYER_BEGIN = 1000;
        public const int G_PLAYER_ID = 1001;    //当前玩家ID				支持操作:	get
        public const int G_PLAYER_Name = 1002;  //玩家名字         				get
        public const int G_PLAYER_LookFace = 1003;  //玩家头像编号						get set
        public const int G_PLAYER_Hair = 1004;  //玩家发型编号						get
        public const int G_PLAYER_Profession = 1005;    //玩家的职业						get set
        public const int G_PLAYER_Level = 1006; //玩家等级							get		 add
        public const int G_PLAYER_MapID = 1007; //玩家所在地图ID  					get
        public const int G_PLAYER_PosX = 1008;  //玩家所在地图X坐标  				get
        public const int G_PLAYER_PosY = 1009;  //玩家所在地图Y坐标				get
        public const int G_PLAYER_Virtue = 1010;    //玩家功德值						get
        public const int G_PLAYER_Meto = 1011;  //玩家转世							get
        public const int G_PLAYER_Sex = 1012;   //玩家性别							get
        public const int G_PLAYER_TeamMemberNum = 1013; //玩家队伍成员数量，没有队伍为0	get
        public const int G_PLAYER_HomeID = 1014;    //玩家房子id						get
        public const int G_PLAYER_AccountId = 1015; //玩家账号id						get
        public const int G_PLAYER_BattleEffect = 1016;  //玩家战斗力						get
        public const int G_PLAYER_MateName = 1017;  //玩家伴侣名称						get
        public const int G_PLAYER_RidingPoints = 1018;  //玩家骑宠积分						get
        public const int G_PLAYER_Life = 1019;  //玩家生命值						get		 add
        public const int G_PLAYER_MaxLife = 1020;   //玩家最大生命值					get
        public const int G_PLAYER_Mana = 1021;  //玩家法力值						get		 add
        public const int G_PLAYER_MaxMana = 1022;   //玩家最大法力值					get
        public const int G_PLAYER_Mentor = 1023;    //玩家点化机会						get		 add
        public const int G_PLAYER_Transfrom = 1024; //变身ID							get	set
        public const int G_PLAYER_Money = 1025; //玩家游戏币						get		 add
        public const int G_PLAYER_MoneyTrial = 1026;    //试炼窟天石操作							 add
        public const int G_PLAYER_EMoney = 1027;    //玩家天石							get		 add
        public const int G_PLAYER_EMoneyMono = 1028;    //玩家赠点							get		 add
        public const int G_PLAYER_Exp = 1029;   //玩家经验(add操作不增加贡献)		get		 add
        public const int G_PLAYER_ExpContribute = 1030; //玩家经验(add操作增加贡献)				 add
        public const int G_PLAYER_PK = 1031;    //玩家PK值							get		 add
        public const int G_PLAYER_Strength = 1032;  //玩家力量值						get		 add
        public const int G_PLAYER_Speed = 1033; //玩家灵巧值		 				get		 add
        public const int G_PLAYER_Health = 1034;    //玩家体力值						get		 add
        public const int G_PLAYER_Soul = 1035;  //玩家精神值						get		 add
        public const int G_PLAYER_SynRank = 1036;   //玩家帮派里排名					get
        public const int G_PLAYER_Iterator = 1037;  //用于在任务系统中叠代			get	set	 add
        public const int G_PLAYER_Crime = 1038; //犯罪时间							get	set
        public const int G_PLAYER_GameCard = 1039;  //cq_card记录数量					get
        public const int G_PLAYER_GameCard2 = 1040; //cq_card2记录数量					get
        public const int G_PLAYER_XP = 1041;    //当前XP值							get	set	 add
        public const int G_PLAYER_EP = 1042;    //体力值							get	set	 add
        public const int G_PLAYER_AddPoint = 1043;  //玩家属性点						get	set	 add
        public const int G_PLAYER_ClientVersion = 1044; //客户的版本						get
        public const int G_PLAYER_Peerage = 1045;   //玩家爵位							get
        public const int G_PLAYER_Businness = 1046; //玩家商人状态						get	set
        public const int G_PLAYER_VIP = 1047;   //玩家VIP等级						get
        public const int G_PLAYER_VIPValue = 1048;  //玩家VIP值							get	set	 add
        public const int G_PLAYER_StorageMoney = 1049;  //玩家存储的钱						get		 add
        public const int G_PLAYER_FirstPro = 1050;  //职业								get
        public const int G_PLAYER_OldPro = 1051;    //前世职业							get
        public const int G_PLAYER_AddMount = 1052;  //坐骑移动力								 add
        public const int G_PLAYER_Cultivation = 1053;   //修行值							get		 add
        public const int G_PLAYER_PKProtocol = 1054;    //PK模式							get	set
        public const int G_PLAYER_StrengthValue = 1055; //气力值							get		 add
        public const int G_PLAYER_SynID = 1056; //帮派ID							get
        public const int G_PLAYER_FamilyID = 1057;  //家族ID							get
        public const int G_PLAYER_LevupExp = 1058;  //升级到下一级所需经验			get
        public const int G_PLAYER_MateID = 1059;    //获得配偶ID						get
        public const int G_PLAYER_GodBless = 1060;  //获得祝福剩余时间				get		 add
        public const int G_PLAYER_TransferDragon20 = 1061;  //玩家转服龙珠20的数量			get
        public const int G_PLAYER_TransferDragon100 = 1062; //玩家转服龙珠100的数量			get
        public const int G_PLAYER_BusinessManDays = 1063;   //商人转正剩余天数				get
        public const int G_PLAYER_GodBlessTime = 1064;  //玩家祝福账号的到期时间		get
        public const int G_PLAYER_ExpPercent = 1065;    //玩家百分比经验(add操作不增加贡献)	get		add
        public const int G_PLAYER_ExpPercentContribute = 1066;  //玩家百分比经验(add操作增加贡献)		add
        public const int G_PLAYER_CultureValue = 1067;  //获取玩家修为值				get add
        public const int G_PLAYER_League_Point = 1068;  //获取玩家黄金联赛积分 		get add
        public const int G_PLAYER_League_ID = 1069; //获取玩家联盟id 		get
        public const int G_PLAYER_Service_Value = 1070; //玩家战功 		get add
        public const int G_PLAYER_League_Official = 1071;   //获取玩家官职 		get 
        public const int G_PLAYER_ExpTime = 1072;   //通过exptime绐玩家加经验	add
        public const int G_PLAYER_Golden_Limit = 1073;  //获取玩家仓库增加的黄金联赛积分
        public const int SCRIPT_PARAM_PLAYER_GONGFU_TOTAL_POWER = 1074;   //获取玩家自创武功总分
        public const int G_PLAYER_ServerID = 1077;  //获取玩家原服务器ID
        public const int G_PLAYER_Beans = 1079;     //获取金豆数量
        public const int SCRIPT_PARAM_PLAYER_SPECIAL_EXP_TIME = 1080;   //特殊经验(无每日上限限制,60分钟要传600) add
        public const int SCRIPT_PARAM_PLAYER_SPECIAL_EXP_PERCENT = 1081; //按百分比增加特殊的玩家经验(不增加贡献) add
        public const int SCRIPT_PARAM_PLAYER_EXP_POOL = 1082;           //经验池经验                        get
        public const int SCRIPT_PARAM_PLAYER_EXP_Surplus = 1083;        //获取玩家身上剩余经验（包含人物经验以及经验池经验）                        get
        public const int SCRIPT_PARAM_PLAYER_EMONEY_TIANMEN = 1085;         //活动通过AddUserInt接口对玩家天石的操作改为用新增的子类型
        public const int SCRIPT_PARAM_PLAYER_Wing_Type = 1086;          //获取玩家当前翅膀皮肤数据                        get
        public const int SCRIPT_PARAM_PLAYER_Title_Type = 1087;             //获取玩家当前称号数据type id                        get
        public const int G_PLAYER_EMONEY_RECYCLE = 1089;                //表示对玩家天石的回收，对应e_money记录类型为110
        public const int G_PLAYER_EMONEY_DRAGONSOUL = 1088;                 //龙魂通过AddUserInt接口对玩家天石的操作改为用新增的子类型
        public const int G_SCRIPT_PARAM_PLAYER_PROF_EXP = 1090;             //表示增加或获得玩家的职业经验
        public const int G_SCRIPT_PARAM_PLAYER_PK = 1091;               //读取和设置PK模式状态
        public const int G_SCRIPT_PARAM_PLAYER_EMONEY_GM_RECYCLE = 1092;    //表示GM回收天石对玩家的天石操作
        public const int G_PLAYER_LAST = 1999;

        public const int G_NPC_BEGIN = 2000;
        public const int G_NPC_ID = 2001;   //取当前NPC的ID			=id=0   
        public const int G_NPC_Name = 2002; //取NPC的姓名            
        public const int G_NPC_OwnerID = 2003;  //取NPC的OwnerID
        public const int G_NPC_OwnerType = 2004;    //取NPC的OwnerType
        public const int G_NPC_Type = 2005; //取NPC的类型        
        public const int G_NPC_LookFace = 2006; //取NPC的Lookface   	                         
        public const int G_NPC_MapID = 2007;    //取NPC所在的地图编号		           
        public const int G_NPC_PosX = 2008; //取NPC所在地图的X坐标		             
        public const int G_NPC_PosY = 2009; //取NPC所在地图的Y坐标	
        public const int G_NPC_Data0 = 2010;    //取NPC身上的Data0值		
        public const int G_NPC_Data1 = 2011;    //取NPC身上的Data1值
        public const int G_NPC_Data2 = 2012;    //取NPC身上的Data2值		   
        public const int G_NPC_Data3 = 2013;    //取NPC身上的Data3值
        public const int G_NPC_DataStr = 2014;  //取NPC身上的DataStr值
        public const int G_NPC_MaxLife = 2015;  //取NPC最大血值
        public const int G_NPC_Life = 2016; //取NPC当前血值
        public const int G_NPC_LAST = 2099;


        public const int G_MAP_BEGIN = 2100;    //2101，2103-2107 要用GetMapInt获取，2103，2108-2111要用GetMapIntEx获取
        public const int G_MAP_ID = 2101;   //取当前地图的ID			=ID=0
        public const int G_MAP_Name = 2102; //取地图的名称
        public const int G_MAP_Type = 2103; //取地图的属性
        public const int G_MAP_OwnerID = 2104;  //取地图主人ID
        public const int G_MAP_RebornMap = 2105;    //取地图重生地图ID
        public const int G_MAP_PosX = 2106; //取地图重生点X坐标
        public const int G_MAP_PosY = 2107; //取地图重生点Y坐标    
        public const int G_MAP_SYNID = 2108;    //帮派地图
        public const int G_MAP_RES_LEV = 2109;  //资源等级
        public const int G_MAP_DOC = 2110;  //mapdoc
        public const int G_MAP_STATUS = 2111;   //设置状态
        public const int G_MAP_RESET_STATUS = 2112; //重置状态
        public const int G_MAP_PORTAL_X = 2113; //取地图入口点X坐标
        public const int G_MAP_PORTAL_Y = 2114; //取地图入口点Y坐标 
        public const int G_MAP_LAST = 2199;


        public const int G_DYNA_GLOBAL_BEGIN = 2200;
        public const int G_DYNA_GLOBAL_ID = 2201;   // cq_dyna_global_data (与表顺序对应=id在lua中无接口)
        public const int G_DYNA_GLOBAL_DATA0 = 2202;
        public const int G_DYNA_GLOBAL_DATA1 = 2203;
        public const int G_DYNA_GLOBAL_DATA2 = 2204;
        public const int G_DYNA_GLOBAL_DATA3 = 2205;
        public const int G_DYNA_GLOBAL_DATA4 = 2206;
        public const int G_DYNA_GLOBAL_DATA5 = 2207;
        public const int G_DYNA_GLOBAL_DATASTR0 = 2208;
        public const int G_DYNA_GLOBAL_DATASTR1 = 2209;
        public const int G_DYNA_GLOBAL_DATASTR2 = 2210;
        public const int G_DYNA_GLOBAL_DATASTR3 = 2211;
        public const int G_DYNA_GLOBAL_DATASTR4 = 2212;
        public const int G_DYNA_GLOBAL_DATASTR5 = 2213;
        public const int G_DYNA_GLOBAL_TIME0 = 2214;
        public const int G_DYNA_GLOBAL_TIME1 = 2215;
        public const int G_DYNA_GLOBAL_TIME2 = 2216;
        public const int G_DYNA_GLOBAL_TIME3 = 2217;
        public const int G_DYNA_GLOBAL_TIME4 = 2218;
        public const int G_DYNA_GLOBAL_TIME5 = 2219;
        public const int G_DYNA_GLOBAL_LAST = 2249;

        public const int G_TASKDETAIL_BEGIN = 2250;
        public const int G_TASKDETAIL_ID = 2251;    // task_detail (与表顺序对应			=id在lua中无接口)
        public const int G_TASKDETAIL_USER_ID = 2252;
        public const int G_TASKDETAIL_TASK_ID = 2253;
        public const int G_TASKDETAIL_COMPLETE_FLAG = 2254;
        public const int G_TASKDETAIL_NOTIFY_FLAG = 2255;
        public const int G_TASKDETAIL_DATA1 = 2256;
        public const int G_TASKDETAIL_DATA2 = 2257;
        public const int G_TASKDETAIL_DATA3 = 2258;
        public const int G_TASKDETAIL_DATA4 = 2259;
        public const int G_TASKDETAIL_DATA5 = 2260;
        public const int G_TASKDETAIL_DATA6 = 2261;
        public const int G_TASKDETAIL_DATA7 = 2262;
        public const int G_TASKDETAIL_TASK_OVERTIME = 2263;
        public const int G_TASKDETAIL_TASK_OVERTIME_SEC = 2264;
        public const int G_TASKDETAIL_TYPE = 2265;
        public const int G_MAX_ACCUMULATE_TIMES = 2266;
        public const int G_TASKDETAIL_LAST = 2299;


        public const int G_ITEM_BEGIN = 2300;
        public const int G_ITEM_ID = 2301;  //物品的ID			=ID=0
        public const int G_ITEM_Type = 2302;    //物品类型
        public const int G_ITEM_OwnerID = 2303; //OwnerID
        public const int G_ITEM_PlayerID = 2304;    //PlayerID
        public const int G_ITEM_Amount = 2305;  //当前耐久
        public const int G_ITEM_AmountLimit = 2306; //耐久上限
        public const int G_ITEM_Ident = 2307;   //是否鉴定
        public const int G_ITEM_Position = 2308;    //位置
        public const int G_ITEM_Gem1 = 2309;    //第一个洞
        public const int G_ITEM_Gem2 = 2310;    //第二个洞
        public const int G_ITEM_Magic1 = 2311;  //第一种魔法效果
        public const int G_ITEM_Magic2 = 2312;  //第二种魔法效果
        public const int G_ITEM_Addition = 2313;    //追加数值			//这个就是G_ITEM_Magic3
        public const int G_ITEM_Data = 2314;    //物品Data字段值
        public const int G_ITEM_ReduceDmg = 2315;   //神佑
        public const int G_ITEM_AddLife = 2316; //生命加持
        public const int G_ITEM_AntiMonster = 2317; //克制怪物
        public const int G_ITEM_Name = 2318;    //名字
        public const int G_ITEM_Color = 2319;   //颜色
        public const int G_ITEM_Monopoly = 2320;    //赠品装备属性
        public const int G_ITEM_AddExp = 2321;  //追加经验
        public const int G_ITEM_DelTime = 2322; //时效性物品删除时间
        public const int G_ITEM_SaveTime = 2323;    //物品有效时间
        public const int G_ITEM_AcutionDeposit = 2324;  //拍卖行保证金
        public const int G_ITEM_ITEM_VALUE = 2330;  //获取物品价值
        public const int G_ITEM_LAST = 2399;

        public const int G_TEAM_BEGIN = 2400;
        public const int G_TEAM_ID = 2401;  //队伍的ID
        public const int G_TEAM_Amount = 2402;  //队伍人数
        public const int G_TEAM_MinLev = 2403;  //组员最低等级
        public const int G_TEAM_MaxLev = 2404;  //组员最高等级
        public const int G_TEAM_MinMoney = 2405;    //组员最少金币
        public const int G_TEAM_Mate = 2406;    //组员是否为伴侣
        public const int G_TEAM_Friend = 2407;  //组员是否为朋友
        public const int G_TEAM_Alive = 2408;   //组员是否都活着
        public const int G_TEAM_LAST = 2499;
        public const int G_ITEM_Data1 = 2325;   //物品data1字段值
        public const int G_ITEM_Data2 = 2326;   //物品data2字段值
        public const int G_ITEM_Data3 = 2327;   //物品data3字段值
        public const int G_ITEM_Data4 = 2328;   //物品data4字段值
        public const int G_ITEM_Data5 = 2329;   //物品data5字段值

        public const int G_TRAP_BEGIN = 2500;   // cq_trap表
        public const int G_TRAP_ID = 2501;
        public const int G_TRAP_TYPE = 2502;
        public const int G_TRAP_LOOK = 2503;
        public const int G_TRAP_OWNER_ID = 2504;    //暂未实现
        public const int G_TRAP_MAPID = 2505;
        public const int G_TRAP_PosX = 2506;
        public const int G_TRAP_PosY = 2507;
        public const int G_TRAP_DATA = 2508;    //暂未实现
        public const int G_TRAP_BOUND_CX = 2509;    //暂未实现
        public const int G_TRAP_BOUND_CY = 2510;    //暂未实现
        public const int G_TRAP_LAST = 2599;

        public const int G_EMONEY_CARD_BEGIN = 2600;    // 天石卡表
        public const int G_EMONEY_CARD1 = 2601; // emoney_card
        public const int G_EMONEY_CARD2 = 2602; // emoney_card2
        public const int G_EMONEY_CARD3 = 2603; // emoney_card3
        public const int G_EMONEY_CARD4 = 2604; // emoney_card4
        public const int G_EMONEY_CARD_END = 2699;

        public const int G_ITEMTYPE_BEGIN = 2700;   //cq_itemtype属性
        public const int G_ITEMTYPE_Name = 2701;    //名字
        public const int G_ITEMTYPE_Profession = 2702;  //职业限制
        public const int G_ITEMTYPE_Skill = 2703;   //武器限制
        public const int G_ITEMTYPE_Level = 2704;   //等级限制
        public const int G_ITEMTYPE_Sex = 2705; //性别限制
        public const int G_ITEMTYPE_Monopoly = 2706;    //独占性
        public const int G_ITEMTYPE_Mask = 2707;    //(贵重物品之类的属性)
        public const int G_ITEMTYPE_EmoneyPrice = 2708; //天石价格
        public const int G_ITEMTYPE_EmoneyMonoPrice = 2709; //赠点价格
        public const int G_ITEMTYPE_SaveTime = 2710;    //保持时间
        public const int G_ITEMTYPE_TypeDesc = 2711;    //类型说明
        public const int G_ITEMTYPE_ItemDesc = 2712;    //物品说明
        public const int G_ITEMTYPE_AccumulateLimit = 2713; //物品叠加数
        public const int G_ITEMTYPE_LAST = 2799;

        public const int G_NPC_COUNT_BEGIN = 2800;
        public const int G_NPC_COUNT_ALL = 2801;    //取玩家地图上所有NPC的数量
        public const int G_NPC_COUNT_FURNITURE = 2802;  //取玩家地图上所有家具的数量
        public const int G_NPC_COUNT_NAME = 2803;   //取玩家地图上所有指定名字的NPC数量
        public const int G_NPC_COUNT_TYPE = 2804;   //取玩家地图上所有指定类型的NPC数量
        public const int G_NPC_COUNT_LAST = 2899;

        public const int G_SYNDICATE_BEGIN = 2800;
        public const int G_SYNDICATE_ALLY_SYN0 = 2801;  //同盟帮派1
        public const int G_SYNDICATE_ALLY_SYN1 = 2802;  //同盟帮派2
        public const int G_SYNDICATE_ALLY_SYN2 = 2803;  //同盟帮派3
        public const int G_SYNDICATE_ALLY_SYN3 = 2804;  //同盟帮派4
        public const int G_SYNDICATE_ALLY_SYN4 = 2805;  //同盟帮派5
        public const int G_SYNDICATE_ALLY_SYN5 = 2806;  //同盟帮派6
        public const int G_SYNDICATE_ALLY_SYN6 = 2807;  //同盟帮派7
        public const int G_SYNDICATE_ALLY_SYN7 = 2808;  //同盟帮派8
        public const int G_SYNDICATE_ALLY_SYN8 = 2809;  //同盟帮派9
        public const int G_SYNDICATE_ALLY_SYN9 = 2810;  //同盟帮派10
        public const int G_SYNDICATE_ALLY_SYN10 = 2811; //同盟帮派11
        public const int G_SYNDICATE_ALLY_SYN11 = 2812; //同盟帮派12
        public const int G_SYNDICATE_ALLY_SYN12 = 2813; //同盟帮派13
        public const int G_SYNDICATE_ALLY_SYN13 = 2814; //同盟帮派14
        public const int G_SYNDICATE_ALLY_SYN14 = 2815; //同盟帮派15
        public const int G_SYNDICATE_ENEMY_SYN0 = 2816; //敌对帮派1
        public const int G_SYNDICATE_ENEMY_SYN1 = 2817; //敌对帮派2
        public const int G_SYNDICATE_ENEMY_SYN2 = 2818; //敌对帮派3
        public const int G_SYNDICATE_ENEMY_SYN3 = 2819; //敌对帮派4
        public const int G_SYNDICATE_ENEMY_SYN4 = 2820; //敌对帮派5
        public const int G_SYNDICATE_ENEMY_SYN5 = 2821; //敌对帮派6
        public const int G_SYNDICATE_ENEMY_SYN6 = 2822; //敌对帮派7
        public const int G_SYNDICATE_ENEMY_SYN7 = 2823; //敌对帮派8
        public const int G_SYNDICATE_ENEMY_SYN8 = 2824; //敌对帮派9
        public const int G_SYNDICATE_ENEMY_SYN9 = 2825; //敌对帮派10
        public const int G_SYNDICATE_ENEMY_SYN10 = 2826;    //敌对帮派11
        public const int G_SYNDICATE_ENEMY_SYN11 = 2827;    //敌对帮派12
        public const int G_SYNDICATE_ENEMY_SYN12 = 2828;    //敌对帮派13
        public const int G_SYNDICATE_ENEMY_SYN13 = 2829;    //敌对帮派14
        public const int G_SYNDICATE_ENEMY_SYN14 = 2830;    //敌对帮派15
        public const int G_SYNDICATE_NAME = 2831;   //帮派名称
        public const int G_SYNDICATE_LEADER_NAME = 2832;    //帮派帮主名称
        public const int G_SYNDICATE_MONEY = 2833;  //帮派基金
        public const int G_SYNDICATE_MEMBER_AMOUNT = 2834;  //帮派成员数量
        public const int G_SYNDICATE_EMONEY = 2835; //帮派天石
        public const int G_SYNDICATE_LEVEL = 2837;  //帮派等级
        public const int SCRIPT_PARAM_SYNDICATE_LEADER_ID = 2838;   //获取帮主id

        public const int G_SYNDICATE_END = 2899;

        public const int G_SYN_MEMBER_ATTR_BEGIN = 2900;
        public const int G_SYN_MEMBER_ATTR_RANK = 2901; //帮派玩家的帮派内等级(指帮主，长老这种)
        public const int G_SYN_MEMBER_ATTR_PROFFER = 2902;  //帮派玩家的游戏币贡献值
        public const int G_SYN_MEMBER_ATTR_END = 2999;


        public const int G_GONGFU_ATTR_BEGIN = 3000;
        public const int G_GONGFU_ATTR_REALM = 3001;    //玩家的功力境界		get
        public const int G_GONGFU_ATTR_FREE_CULTIVATE_PARAM = 3002; //玩家免费修炼参数		get	set	add
        public const int G_GONGFU_ATTR_GENUINEQI_LV = 3003; //玩家真气等级			get	set	add
        public const int G_GONGFU_ATTR_END = 3099;

        public const int G_MONSTER_BEGIN = 3100;    //怪物
        public const int G_MONSTER_ID = 3101;
        public const int G_MONSTER_Name = 3102;
        public const int G_MONSTER_Type = 3103;
        public const int G_MONSTER_MapID = 3104;
        public const int G_MONSTER_PosX = 3105;
        public const int G_MONSTER_PosY = 3106;
        public const int G_MONSTER_MaxLife = 3107;
        public const int G_MONSTER_Life = 3108;
        public const int G_MONSTER_Level = 3109;
        public const int G_MONSTER_LAST = 3199;
    }
}
