namespace Long.Network.Packets
{
    /// <summary>
    ///     Packet types for the Conquer Online game client across all server projects.
    ///     Identifies packets by an unsigned short from offset 2 of every packet sent to
    ///     the server.
    /// </summary>
    public enum PacketType : ushort
    {
        MsgRegister = 1001,
        MsgTalk = 1004,
        MsgUserInfo = 1006,
        MsgItemInfo = 1008,
        MsgItem = 1009,
        MsgTick = 1012,
        MsgName = 1015,
        MsgWeather,
        MsgFriend = 1019,
        MsgInteract = 1022,
        MsgTeam = 1023,
        MsgAllot = 1024,
        MsgWeaponSkill = 1025,
        MsgTeamMember = 1026,
        MsgGemEmbed = 1027,
        MsgFuse = 1028,
        MsgTeamAward = 1029,
        MsgBattleEffectiveness = 1032,
        MsgData = 1033,
        MsgDetainItemInfo = 1034,
        MsgGodExp = 1036,
        MsgPing = 1037,
        MsgSolidify = 1038,
        MsgPlayerAttribInfo = 1040,
        MsgEnemyList = 1041,
        MsgMonsterTransform = 1042,
        MsgTeamRoll = 1043,
        MsgLoadMap = 1044,
        MsgMailOperation = 1045,
        MsgMailList = 1046,
        MsgMailNotify = 1047,
        MsgMailContent = 1048,
        MsgPCServerConfig = 1049,
        MsgTrade = 1056,
        // MsgAccount = 1051,
        MsgConnect = 1052,
        MsgConnectEx = 1055,
        MsgSynpOffer = 1058,
        MsgEncryptCode = 1059,
        //MsgAccount = 1060,
        MsgDutyMinContri = 1061,
        MsgSynCompete = 1062,
        MsgSelfSynMemAwardRank = 1063,
        MsgSponsor = 1065,
        MsgMeteSpecial = 1066,
        MsgLoginNotice = 1067,
        MsgHangUp = 1070,
        MsgCompeteRank = 1071,
        MsgCampFight = 1072,
        MsgCampInfo = 1073,
        MsgCheatingProgram = 1081,
        //MsgAccount = 1086,
        MsgPCNum = 1100,
        MsgMapItem = 1101,
        MsgPackage = 1102,
        MsgMagicInfo = 1103,
        MsgFlushExp = 1104,
        MsgMagicEffect = 1105,
        MsgSyndicateAttributeInfo = 1106,
        MsgSyndicate = 1107,
        MsgItemInfoEx = 1108,
        MsgNpcInfoEx = 1109,
        MsgMapInfo = 1110,
        MsgMessageBoard = 1111,
        MsgSynMemberInfo = 1112,
        MsgDice = 1113,
        MsgSyncAction = 1114,
        MsgDisconnect = 1115,

        MsgInviteTrans = 1126,
        MsgMentorPlayer = 1127,
        MsgVipUserHandle = 1128,
        MsgVipFunctionValidNotify = 1129,
        MsgTitle = 1130,

        MsgTaskStatus = 1134,
        MsgTaskDetailInfo = 1135,
        MsgAchievement = 1136,

        MsgFlower = 1150,
        MsgRank = 1151,
        MsgMagicEffectTime = 1152,
        MsgMagicColdTime = 1153,

        MsgFamily = 1312,
        MsgFamilyOccupy = 1313,
        MsgLottery = 1314,
        MsgOperatingAct = 1315,
        MsgOperatingActInfo = 1316,

        MsgAuction = 1320,
        MsgAuctionItem = 1321,
        MsgAuctionQuery = 1322,
        MsgPromotionAct = 1323,
        MsgPromotionInfo = 1324,

        MsgSlotAction = 1351,
        MsgSlotResult = 1352,

        MsgAccount = 1542,

        MsgNpcInfo = 2030,
        MsgNpc = 2031,
        MsgTaskDialog = 2032,
        MsgFriendInfo = 2033,
        MsgPetInfo = 2035,
        MsgDataArray = 2036,
        MsgTrainingInfo = 2043,
        MsgTraining = 2044,
        MsgAuraGroup = 2045,
        MsgTradeBuddy = 2046,
        MsgTradeBuffyInfo = 2047,
        MsgEquipLock = 2048,
        MsgPigeon = 2050,
        MsgPigeonQuery = 2051,
        MsgNobility = 2064,
        MsgGuide = 2065,
        MsgGuideInfo = 2066,
        MsgGuideContribute = 2067,
        MsgQuiz = 2068,
        MsgSuitStatus = 2070,
        MsgRelation = 2071,
        MsgRaceTrackProp = 2072,
        MsgRaceTrackPropEffect = 2073,
        MsgRaceTrackStatus = 2075,
        MsgQuench = 2076,
        MsgItemStatus = 2077,

        MsgUserIpInfo = 2078,
        MsgServerInfo = 2079,
        MsgChangeName = 2080,
        MsgDeadMark = 2081,
        MsgUserCityInfo = 2082,
        MsgItemDialog = 2083,
        MsgShowHandKick = 2088,
        MsgShowHandRaceInteractive = 2089,
        MsgShowHandEnter = 2090,
        MsgShowHandDealtCard = 2091,
        MsgShowHandActivePlayer = 2092,
        MsgShowHandCallAction = 2093,
        MsgShowHandLayCard = 2094,
        MsgShowHandGameResult = 2095,
        MsgShowHandExit = 2096,
        MsgShowHandOnlineStatus = 2097,
        MsgShowHandLostInfo = 2098,
        MsgShowHandTrusteeship = 2099,

        MsgFactionRankInfo = 2101,
        MsgSynMemberList = 2102,
        MsgSynChgDomName = 2103,
        MsgSuperFlag = 2110,

        MsgLeaveWord = 2170,

        MsgTexasInteractive = 2171,
        MsgTexasNpcInfo = 2172,
        MsgGamblingTableOpt = 2173,
        MsgGamblingTablePlayerList = 2174,
        MsgGamblingTableInfo = 2175,
        MsgGamblingResult = 2176,
        MsgChipsExpression = 2177,
        MsgPotHistory = 2178,
        MsgPlayerResult = 2179,
        MsgGameTrend = 2180,
        MsgGamblingNpc = 2181,

        MsgTotemPoleInfo = 2201,
        MsgWeaponsInfo = 2202,
        MsgTotemPole = 2203,
        MsgTotemsRegister = 2204,

        MsgQualifyingInteractive = 2205,
        MsgQualifyingFightersList = 2206,
        MsgQualifyingRank = 2207,
        MsgQualifyingSeasonRankList = 2208,
        MsgQualifyingDetailInfo = 2209,
		MsgQualifyingScore = 2210,
		MsgQualifyingWitness = 2211,

        MsgElitePKArenic = 2218,
        MsgPkEliteMatchInfo = 2219,
        MsgPkStatistic = 2220,
        MsgPkEnable = 2221,
        MsgElitePkScore = 2222,
        MsgElitePkGameRankInfo = 2223,
        MsgWarFlag = 2224,
        MsgSynRecuitAdvertising = 2225,
        MsgSynRecruitAdvertisingList = 2226,
        MsgSynRecruitAdvertisingOpt = 2227,

        MsgTeamPKArenic = 2230,
        MsgTeamPKArenicScore = 2231,
        MsgTeamPKMatchInfo = 2232,
        MsgTeamPKRankInfo = 2233,

		MsgPKEliteAction = 2239,
		MsgDominateTeamName = 2240,		
        
        MsgTeamArenaInteractive = 2241,
        MsgTeamArenaFightingTeamList = 2242,
        MsgTeamArenaRank = 2243,
        MsgTeamArenaYTop10List = 2244,
        MsgTeamArenaHeroData = 2245,
        MsgTeamArenaScore = 2246,
        MsgTeamArenaFightingMemberInfo = 2247,

        MsgTeamPopPKArenic = 2250,
        MsgTeamPopPKArenicScore = 2251,
        MsgTeamPopPKMatchInfo = 2252,
        MsgTeamPopPKRankInfo = 2253,
        MsgDominateTeamPopPkName = 2260,

        Msg2ndPsw = 2261,
        MsgPaint = 2262,

        MsgSubPro = 2320,
        MsgFactionMatch = 2330,
        MsgFMRoundRobin = 2331,
        MsgFMMatch = 2332,
        MsgFactionMatchWitness = 2333,

        MsgTransportor = 2400,
        MsgAura = 2410,
        MsgVerifyCheck = 2420,
        MsgNationality = 2430,
        MsgAthleteShop = 2440,
        MsgExchangeShopGoods = 2441,
        MsgExchangeShop = 2442,
        MsgExchangeShopBuy = 2443,

        MsgServerList = 2500,
        MsgCrossSwitch = 2501,
        MsgCrossFlagWar = 2502,
        MsgCrossFlagWarMerit = 2504,
        MsgCrossFlagWarAltar = 2505,
        MsgCrossFlagWarFlag = 2506,
        MsgCrossFlagWarRank = 2507,
        MsgFactionChiefBase = 2510,
        MsgStrCheckKey = 2520,

        MsgTrainingVitality = 2533,
        MsgTrainingVitalityInfo = 2534,
        MsgTrainingVitalityScore = 2535,
        MsgTrainingVitalityProtect,
        MsgTrainingVitalityProtectInfo,
        MsgTrainingVitalityExpiryNotify,

        MsgGLRankingList = 2600,
        MsgGLHeroDetail = 2601,
        MsgGLLastSeasonTopScore = 2602,
        MsgGLChampionList = 2603,
        MsgGLInteractive = 2604,

        MsgInnerStrengthOpt = 2610,
        MsgInnerStrengthInfo = 2611,
        MsgInnerStrengthTotalInfo = 2612,
        MsgExchangeInnerStrength = 2613,

        MsgCountryInfo = 2620,
        MsgCountryOpt = 2621,

        MsgLeagueOpt = 2622,
        MsgLeagueInfo = 2623,
        MsgLeagueAllegianceList = 2624,
        MsgLeagueSynList = 2625,
        MsgLeagueMemList = 2626,
        MsgLeagueRank = 2627,
        MsgLeaguePalaceGuardsList = 2628,
        MsgLeagueImperialCourtList = 2629,
        MsgLeagueOrderStatus = 2630,
        MsgOverheadLeagueInfo = 2631,
        MsgLeagueToken = 2633,
        MsgLeagueConcubines = 2634,
        MsgLeagueRobList = 2640,
        MsgLeagueBeRob = 2641,
        MsgLeagueRobOpt = 2642,
        MsgTokenUpdate = 2643,

        MsgOwnKongfuBase = 2700,
        MsgOwnKongfuImproveSummaryInfo = 2701,
        MsgOwnKongfuImproveFeedback = 2702,
        MsgOwnKongRank = 2703,
        MsgOwnKongfuPkSetting = 2704,

        MsgMagicCoat = 2710,
        MsgBenefitsConfig = 2712,

        MsgRouletteWinningNumber = 2801,
        MsgRouletteLatestProfitLossList = 2802,
        MsgRouletteWatcherList = 2803,
        MsgRouletteAction = 2804,
        MsgRoulette1ArgAction = 2805,
        MsgRouletteInvite = 2806,
        MsgRouletteNpcInfo = 2807,
        MsgRouletteTable = 2808,
        MsgRoulettePlayer = 2809,
        MsgRoulettePlayerBet = 2810,

        MsgTaskReward = 2811,
        MsgTenTimesLotteryReward = 2813,

        MsgActivityTask = 2820,
        MsgActivityTaskReward = 2822,
        MsgStatisticDaily = 2823,

        MsgProcessGoalTaskOpt = 2830,
        MsgProcessGoalTask = 2831,
        MsgProcessGoalInfo = 2832,

        MsgOSAction = 2900,
        MsgOSConnectInfo = 2901,
        MsgOSEnter = 2902,

        MsgTaskAccumulate = 3000,
        MsgHandBrickInfo = 3001,
        MsgOsShop = 3002,
        MsgInvadeWarning = 3100,

        MsgSignIn = 3200,

        MsgItemRefine = 3250,
        MsgItemRefineOpt = 3251,
        MsgUserTotalRefineLevel = 3252,
        MsgUserAbilityScore = 3253,
        MsgRefineEffect = 3254,
        MsgItemRefineRecord = 3255,
        MsgEquipRefineRank = 3256,

        MsgCoatStorage = 3300,
        MsgTitleStorage = 3301,

        MsgTexasExInteractive = 3400,
        MsgTexasExMatchFieldList = 3401,
        MsgTexasExChampionshipList = 3402,
        MsgTexasPersonalInfo = 3403,
        MsgTexasExChampionshipRank = 3404,
        MsgTexasExMyChampionshipRank = 3405,
        MsgTexasChampionshipTableChip = 3406,
        MsgCasinoInteractive = 3420,

        MsgWalk = 10005,
        MsgAction = 10010,
        MsgPlayer = 10014,
        MsgUserAttrib = 10017,

        // Account server packets
        MsgLoginStart = 30000,
        MsgLoginRealmAuth,
        MsgLoginRealmAuthEx,
        MsgLoginUserExchange,
        MsgLoginUserExchangeEx,
        MsgLoginAction,
        MsgLoginInformation,
        MsgLoginPlayerExchange,
        MsgLoginPlayerStatus,
        MsgLoginCmd,
        MsgLoginPing,
        MsgLoginGameInformation,
        MsgLoginRequestUserId,
        MsgLoginSubmitCrossInfo,
        MsgLoginRealmChildInfo,
        MsgLoginCrossServerCredentials,
        MsgLoginEnd = 30999,

		// NPC Server packets
		MsgAiServerStart = 31000,

		MsgAiLoginHandshake,
		MsgAiLoginExchange,
		MsgAiLoginExchangeEx,
		MsgAiPing,
		MsgAiAction,
		MsgAiSpawnNpc,
		MsgAiPlayerLogin,
		MsgAiPlayerLogout,
		MsgAiRoleStatusFlag,
		MsgAiGeneratorManage,
		MsgAiDynaMap,
		MsgAiRoleLogin,
		MsgAiRoleLogout,
		MsgAiInteract,

		MsgAiServerEnd = 31999,

		MsgUpdStart = 32000,
		MsgUpdHandshake,
		MsgUpdHandshakeEx,
		MsgUpdLogin,
		MsgUpdLoginEx,
		MsgUpdQueryVersion,
		MsgUpdPatchList,
		MsgUpdCheckHash,
		MsgUpdConfirmHash,
		MsgUpdPing,

		MsgUpdEnd = 32999,

		/*
         * Piglet is GM Service!
         * Those messages generate interaction between the GM Panel in the web interface and
         * the game servers. Packets are shared between Game <-> Piglet <-> GM Panel
         */
		MsgPigletStart = 33000,
		MsgPigletHandshake,
		MsgPigletLogin,
		MsgPigletLoginEx,
		MsgPigletPing,
		MsgPigletUserBan,
		MsgPigletUserMail,
		MsgPigletUserMassMail,
		MsgPigletUserLogin,
		MsgPigletItemSuspicious,
		MsgPigletUserCount,
		MsgPigletRealmStatus,
		MsgPigletRealmAnnounceMaintenance,
		MsgPigletUserCreditInfo,
		MsgPigletUserCreditInfoEx,
		MsgPigletRealmUpdateCheck,
		MsgPigletClaimFirstCredit,
		MsgPigletLogOutputRedirect,
		MsgPigletShutdown,
		MsgPigletRealmAction,
		MsgPigletEnd = 33999,

		MsgDiscordStart = 34000,
        MsgDiscordEnd = 34999,

        MsgLongHandshake = 40001,
        MsgLongLogin,
        MsgLongLoginEx,

        MsgLongAntiCheatStart = 35000,
        MsgLongAntiCheatAddClient,
        MsgLongAntiCheatCheckClient,
        MsgLongAntiCheatChangeConnectionId,
        MsgLongAntiCheatProcessWarning,
        MsgLongAntiCheatProcessList,

        MsgCrossStart = 36000,
        MsgCrossLogin,
        MsgCrossLoginEx,
        MsgCrossRequestSwitch,
        MsgCrossRequestSwitchEx,
        MsgCrossBroadcastPacket,
        MsgCrossRedirectUserPacket,
        MsgCrossRedirectToUserPacket,
        MsgCrossRealmAction,
        MsgCrossUserInfo,
        MsgCrossItemInfo,
        MsgCrossWeaponSkillInfo,
        MsgCrossMagicInfo,
        MsgCrossAstProfInfo,
        MsgCrossTrainingVitalityInfo,
        MsgCrossOwnKongFuInfo,
        MsgCrossNeigongInfo,
        MsgCrossLimit = 36999
    }
}
